[workspace]
members = [
    "crates/codegen",
    "crates/glossa",
    "crates/shared",
    "crates/l10n",
    "crates/cli",
    "crates/ui",
]
resolver = "3"

[workspace.package]
authors = ["Moe <m@tmoe.me>"]
edition = "2024"
version = "0.0.1"
license = "Apache-2.0"
keywords = ["i18n", "l10n"]
categories = ["internationalization", "localization"]
repository = "https://github.com/2moe/glossa"
rust-version = "1.85.0"

[workspace.dependencies]
getset = "0.1"
log = "0.4"
phf = { version = "0.11", default-features = false }
phf_codegen = "0.11"
phf_shared = { version = "0.11", default-features = false }
ahash = "0.8"
anyhow = "1.0"
tap = "1.0"
thiserror = { version = "2.0", default-features = false }
env_logger = { version = "0.11", default-features = false, features = [
    "humantime",
    "auto-color",
] }
itertools = { version = "0.14", default-features = false, features = [
    "use_alloc",
] }
smallvec = "2.0.0-alpha.11"
collect-with = "0.0.2"

# codegen
ron = "0.10.1"
serde_json = "1.0"
serde_yml = "0.0.12"
toml = "0.8"
kstring = "2.0"
nom = "8.0"
rayon = "1.10"
walkdir = "2.5"
bincode = { version = "2.0", default-features = false }
compact_str = { version = "0.9", default-features = false }
serde_json5 = { version = "0.2", default-features = false }
dashmap = "6.1"
derive_more = { version = "2.0.1", default-features = false }

[workspace.dependencies.glossa-shared]
path = "./crates/shared"
version = "0.0.1"

[workspace.dependencies.glossa-l10n]
path = "./crates/l10n"
version = "0.0.1"

[workspace.dependencies.testutils]
version = "0.0.5"
default-features = false
path = "../testutils"

[workspace.dependencies.serde]
default-features = false
features = ["derive"]
version = "1.0"

[workspace.dependencies.lang-id]
version = "0.0.18"
default-features = false
path = "../lang-id"

[workspace.dependencies.hlight]
version = "0.0.10"
path = "../hlight/crates/hlight"
# path = "../hlight"

[workspace.dependencies.glossa-codegen]
version = "0.0.2-alpha.0"
path = "crates/codegen"

[workspace.dependencies.glossa-dsl]
default-features = false
version = "0.0.15"
# path = "../tmpl-resolver"

[workspace.lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ['cfg(__unstable_doc)']

[package]
name = "tests"
edition.workspace = true

[dev-dependencies]
bincode = { workspace = true, features = ["serde", "std"] }
serde.workspace = true
itertools.workspace = true
testutils = { workspace = true, features = ["os_cmd", "std"] }
phf = { workspace = true, features = ["macros", "serde"] }
ahash = { workspace = true, features = ["serde"] }
ron.workspace = true
anyhow.workspace = true
serde_json.workspace = true
compact_str = { workspace = true, features = ["serde"] }
smallvec.workspace = true
glossa-codegen.workspace = true
env_logger.workspace = true
glossa = { path = "crates/glossa" }
log.workspace = true
collect-with.workspace = true
tap.workspace = true
toml.workspace = true
glossa-shared = { workspace = true, features = ["consts"] }

[dependencies]
# thiserror = "2.0.11"
# hlight = { path = "./crates/hlight" }
