[package]
name = "glossa-ui"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
keywords = ["i18n", "l10n", "TUI", "user-interface"]
categories = ["internationalization", "command-line-interface"]
# categories.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "__unstable_doc"]

[lints]
workspace = true
