[package]
name = "glossa"
version.workspace = true
authors.workspace = true
categories.workspace = true
readme = "../../docs/Readme.md"
edition.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "A language international (i18n) library"

[features]
default = ["std"]
std = [
    "testutils/std",
    "lang-id/sys-locale",
    "thiserror/std",
    "glossa-l10n/error",
    "glossa-l10n/lang-id",
]

[dependencies]
thiserror.workspace = true
lang-id = { workspace = true, features = ["map", "match", "compact_str"] }
log.workspace = true
smallvec.workspace = true
compact_str.workspace = true
collect-with.workspace = true
tap.workspace = true
itertools.workspace = true
testutils.workspace = true
glossa-l10n.workspace = true

[dev-dependencies]
anyhow.workspace = true
env_logger.workspace = true
itertools.workspace = true

[build-dependencies]
glossa-codegen.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "__unstable_doc"]

[lints]
workspace = true
