[package]
name = "glossa-cli"
authors.workspace = true
edition.workspace = true
# version.workspace = true
version = "0.0.1"
license.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords = ["i18n", "l10n", "cli"]
categories = ["internationalization", "command-line-interface"]
readme = "./docs/Readme.md"
description = "A command-line (binary) tool that generates Rust source code or bincode files containing localized text by calling the glossa-codegen API."

[dependencies]
ahash.workspace = true
clap = { version = "4.5.35", features = ["color", "derive", "unicode"] }
directories.workspace = true
env_logger.workspace = true
getset.workspace = true
glossa.workspace = true
glossa-codegen = { workspace = true, features = [
    "toml",
    # "yaml",
    # "highlight",
    # "ron",
    # "json5",
    "json",
] }
# glossa-shared.workspace = true
log.workspace = true
time = "0.3.41"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "__unstable_doc"]

[lints]
workspace = true

[features]
highlight = ["glossa-codegen/highlight"]
json5 = ["glossa-codegen/json5"]
yaml = ["glossa-codegen/yaml"]
ron = ["glossa-codegen/ron"]
# json = ["glossa-codegen/json"]

default = [
    "highlight",
    "json5",
    "yaml",
    "ron",
    #
    "l10n-all",
    # "l10n-zh",
    # "l10n-en",
    # "l10n-en-GB",
    # "l10n-es",
    # "l10n-hi",
    # "l10n-pt",
    # "l10n-bn",
    # "l10n-ru",
    # "l10n-fr",
    # "l10n-ja",
    # "l10n-ar",
    # "l10n-de",
]
l10n-af = []
l10n-ak = []
l10n-am = []
l10n-ar = []
l10n-as = []
l10n-az = []
l10n-bal = []
l10n-be = []
l10n-bem = []
l10n-bg = []
l10n-bho = []
l10n-bm = []
l10n-bn = []
l10n-bs = []
l10n-ca = []
l10n-ceb = []
l10n-cgg = []
l10n-ckb = []
l10n-co = []
l10n-cs = []
l10n-cy = []
l10n-da = []
l10n-de = []
l10n-doi = []
l10n-el = []
l10n-en = []
l10n-en-GB = []
l10n-eo = []
l10n-es = []
l10n-et = []
l10n-eu = []
l10n-fa = []
l10n-fi = []
l10n-fil = []
l10n-fr = []
l10n-fur = []
l10n-fy = []
l10n-ga = []
l10n-gd = []
l10n-gl = []
l10n-gu = []
l10n-ha = []
l10n-he = []
l10n-hi = []
l10n-hr = []
l10n-ht = []
l10n-hu = []
l10n-hy = []
l10n-id = []
l10n-ig = []
l10n-is = []
l10n-it = []
l10n-ja = []
l10n-ja-Latn-JP = []
l10n-jv = []
l10n-ka = []
l10n-kk = []
l10n-km = []
l10n-kn = []
l10n-ko = []
l10n-ku = []
l10n-ky = []
l10n-la = []
l10n-lb = []
l10n-lg = []
l10n-ln = []
l10n-lo = []
l10n-lt = []
l10n-luo = []
l10n-lv = []
l10n-mai = []
l10n-mfe = []
l10n-mg = []
l10n-mi = []
l10n-mk = []
l10n-ml = []
l10n-mn = []
l10n-mr = []
l10n-ms = []
l10n-mt = []
l10n-my = []
l10n-ne = []
l10n-nl = []
l10n-no = []
l10n-nus = []
l10n-ny = []
l10n-om = []
l10n-or = []
l10n-pa = []
l10n-pl = []
l10n-ps = []
l10n-pt = []
l10n-qu = []
l10n-ro = []
l10n-ru = []
l10n-rw = []
l10n-sah = []
l10n-sat = []
l10n-sd = []
l10n-si = []
l10n-sk = []
l10n-sl = []
l10n-sm = []
l10n-sn = []
l10n-so = []
l10n-sq = []
l10n-sr = []
l10n-st = []
l10n-su = []
l10n-sv = []
l10n-sw = []
l10n-ta = []
l10n-te = []
l10n-tg = []
l10n-th = []
l10n-ti = []
l10n-tk = []
l10n-tr = []
l10n-tt = []
l10n-ug = []
l10n-uk = []
l10n-ur = []
l10n-uz = []
l10n-vi = []
l10n-xh = []
l10n-yi = []
l10n-yo = []
l10n-zh = []
l10n-zh-Hant = []
l10n-zh-Latn-CN = []
l10n-zu = []
l10n-all = [
    "l10n-af",
    "l10n-ak",
    "l10n-am",
    "l10n-ar",
    "l10n-as",
    "l10n-az",
    "l10n-bal",
    "l10n-be",
    "l10n-bem",
    "l10n-bg",
    "l10n-bho",
    "l10n-bm",
    "l10n-bn",
    "l10n-bs",
    "l10n-ca",
    "l10n-ceb",
    "l10n-cgg",
    "l10n-ckb",
    "l10n-co",
    "l10n-cs",
    "l10n-cy",
    "l10n-da",
    "l10n-de",
    "l10n-doi",
    "l10n-el",
    "l10n-en",
    "l10n-en-GB",
    "l10n-eo",
    "l10n-es",
    "l10n-et",
    "l10n-eu",
    "l10n-fa",
    "l10n-fi",
    "l10n-fil",
    "l10n-fr",
    "l10n-fur",
    "l10n-fy",
    "l10n-ga",
    "l10n-gd",
    "l10n-gl",
    "l10n-gu",
    "l10n-ha",
    "l10n-he",
    "l10n-hi",
    "l10n-hr",
    "l10n-ht",
    "l10n-hu",
    "l10n-hy",
    "l10n-id",
    "l10n-ig",
    "l10n-is",
    "l10n-it",
    "l10n-ja",
    "l10n-ja-Latn-JP",
    "l10n-jv",
    "l10n-ka",
    "l10n-kk",
    "l10n-km",
    "l10n-kn",
    "l10n-ko",
    "l10n-ku",
    "l10n-ky",
    "l10n-la",
    "l10n-lb",
    "l10n-lg",
    "l10n-ln",
    "l10n-lo",
    "l10n-lt",
    "l10n-luo",
    "l10n-lv",
    "l10n-mai",
    "l10n-mfe",
    "l10n-mg",
    "l10n-mi",
    "l10n-mk",
    "l10n-ml",
    "l10n-mn",
    "l10n-mr",
    "l10n-ms",
    "l10n-mt",
    "l10n-my",
    "l10n-ne",
    "l10n-nl",
    "l10n-no",
    "l10n-nus",
    "l10n-ny",
    "l10n-om",
    "l10n-or",
    "l10n-pa",
    "l10n-pl",
    "l10n-ps",
    "l10n-pt",
    "l10n-qu",
    "l10n-ro",
    "l10n-ru",
    "l10n-rw",
    "l10n-sah",
    "l10n-sat",
    "l10n-sd",
    "l10n-si",
    "l10n-sk",
    "l10n-sl",
    "l10n-sm",
    "l10n-sn",
    "l10n-so",
    "l10n-sq",
    "l10n-sr",
    "l10n-st",
    "l10n-su",
    "l10n-sv",
    "l10n-sw",
    "l10n-ta",
    "l10n-te",
    "l10n-tg",
    "l10n-th",
    "l10n-ti",
    "l10n-tk",
    "l10n-tr",
    "l10n-tt",
    "l10n-ug",
    "l10n-uk",
    "l10n-ur",
    "l10n-uz",
    "l10n-vi",
    "l10n-xh",
    "l10n-yi",
    "l10n-yo",
    "l10n-zh",
    "l10n-zh-Hant",
    "l10n-zh-Latn-CN",
    "l10n-zu",
]
