[package]
name = "glossa-cli"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
keywords = ["i18n", "l10n", "cli"]
categories = ["internationalization", "command-line-interface"]
repository.workspace = true
rust-version.workspace = true

[dependencies]
ahash.workspace = true
clap = { version = "4.5.35", features = ["color", "derive", "unicode"] }
env_logger.workspace = true
getset.workspace = true
glossa.workspace = true
# glossa = { version = "0.0.1", path = "../glossa" }
# compact_str = { workspace = true, features = ["std"] }
glossa-codegen = { workspace = true, features = [
    "toml",
    "yaml",
    "highlight",
    "json",
    "json5",
    "ron",
] }
log.workspace = true
time = "0.3.41"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "__unstable_doc"]

[lints]
workspace = true
