/// Provides compile-time language tag fallback mappings.
///
/// Maps IANA language subtags to their primary fallback language and optional
/// secondary fallbacks, following Unicode CLDR fallback rules
///
/// ## Example
///
/// ```ignore
/// use glossa::cldr_fallback_mapping;
///
/// let gsw = cldr_fallback_mapping(b"gsw");
/// assert_eq!(gsw, &["de"]);
///
/// let en_au = cldr_fallback_mapping(b"en-AU");
/// assert_eq!(en_au, &["en-GB"]);
///
/// let en_ca = cldr_fallback_mapping(b"en-CA");
/// assert_eq!(en_ca, &["en-US"]);
///
/// let unknown = cldr_fallback_mapping(b"und-UN");
/// assert!(unknown.is_empty());
/// ```
pub const fn cldr_fallback_mapping(language: &[u8]) -> &[&str] {
  match language {
    b"aae" => &["sq"],
    b"aao" => &["ar"],
    b"aat" => &["sq"],
    b"ab" => &["ru"],
    b"abh" => &["ar"],
    b"abv" => &["ar"],
    b"ach" => &["en"],
    b"acm" => &["ar"],
    b"acq" => &["ar"],
    b"acw" => &["ar"],
    b"acx" => &["ar"],
    b"acy" => &["ar"],
    b"adf" => &["ar"],
    b"aeb" => &["ar"],
    b"aec" => &["ar"],
    b"af" => &["en"],
    b"afb" => &["ar"],
    b"aii" => &["syr"],
    b"ak" => &["en"],
    b"aln" => &["sq"],
    b"am" => &["en"],
    b"am-Ethi" => &["en-Latn"],
    b"apc" => &["ar"],
    b"apd" => &["ar"],
    b"ar-DZ" => &["ar-MA", "ar-TN", "ar-LY", "ar-MR", "ar-EH"],
    b"ar-EH" => &["ar-MA", "ar-DZ", "ar-TN", "ar-LY", "ar-MR"],
    b"ar-LY" => &["ar-MA", "ar-DZ", "ar-TN", "ar-MR", "ar-EH"],
    b"ar-Latn" => &["ar-Arab"],
    b"ar-MA" => &["ar-DZ", "ar-TN", "ar-LY", "ar-MR", "ar-EH"],
    b"ar-MR" => &["ar-MA", "ar-DZ", "ar-TN", "ar-LY", "ar-EH"],
    b"ar-TN" => &["ar-MA", "ar-DZ", "ar-LY", "ar-MR", "ar-EH"],
    b"arq" => &["ar"],
    b"ars" => &["ar"],
    b"ary" => &["ar"],
    b"arz" => &["ar"],
    b"auz" => &["ar"],
    b"avl" => &["ar"],
    b"ay" => &["es"],
    b"ayh" => &["ar"],
    b"ayl" => &["ar"],
    b"ayn" => &["ar"],
    b"ayp" => &["ar"],
    b"az" => &["ru"],
    b"az-Latn" => &["ru-Cyrl"],
    b"azb" => &["az"],
    b"bal" => &["ur"],
    b"bbz" => &["ar"],
    b"be" => &["ru"],
    b"bem" => &["en"],
    b"bh" => &["hi"],
    b"bhr" => &["mg"],
    b"bjn" => &["ms"],
    b"bjq" => &["mg"],
    b"bmm" => &["mg"],
    b"bn" => &["en"],
    b"bn-Beng" => &["en-Latn"],
    b"bn-Latn" => &["bn-Beng"],
    b"bo" => &["zh"],
    b"bo-Tibt" => &["zh-Hans"],
    b"br" => &["fr"],
    b"btj" => &["ms"],
    b"bve" => &["ms"],
    b"bvu" => &["ms"],
    b"bzc" => &["mg"],
    b"ca" => &["es"],
    b"cdo" => &["zh"],
    b"ceb" => &["fil"],
    b"chr" => &["en"],
    b"cjy" => &["zh"],
    b"ckb" => &["ar"],
    b"co" => &["fr"],
    b"coa" => &["ms"],
    b"cpx" => &["zh"],
    b"crs" => &["fr"],
    b"cs" => &["sk"],
    b"cy" => &["en"],
    b"czh" => &["zh"],
    b"czo" => &["zh"],
    b"da" => &["no", "nb"],
    b"dty" => &["ne"],
    b"dup" => &["ms"],
    b"ee" => &["en"],
    b"en-001" => &[
      "en-US", "en-AS", "en-CA", "en-GU", "en-MH", "en-MP", "en-PH", "en-PR",
      "en-UM", "en-VI",
    ],
    b"en-150" => &["en-GB"],
    b"en-AE" => &["en-GB"],
    b"en-AG" => &["en-GB"],
    b"en-AI" => &["en-GB"],
    b"en-AS" => &[
      "en-US", "en-001", "en-CA", "en-GU", "en-MH", "en-MP", "en-PH", "en-PR",
      "en-UM", "en-VI",
    ],
    b"en-AT" => &["en-GB"],
    b"en-AU" => &["en-GB"],
    b"en-BB" => &["en-GB"],
    b"en-BE" => &["en-GB"],
    b"en-BI" => &["en-GB"],
    b"en-BM" => &["en-GB"],
    b"en-BS" => &["en-GB"],
    b"en-BW" => &["en-GB"],
    b"en-BZ" => &["en-GB"],
    b"en-CA" => &[
      "en-US", "en-001", "en-AS", "en-GU", "en-MH", "en-MP", "en-PH", "en-PR",
      "en-UM", "en-VI",
    ],
    b"en-CC" => &["en-GB"],
    b"en-CH" => &["en-GB"],
    b"en-CK" => &["en-GB"],
    b"en-CM" => &["en-GB"],
    b"en-CX" => &["en-GB"],
    b"en-CY" => &["en-GB"],
    b"en-DE" => &["en-GB"],
    b"en-DG" => &["en-GB"],
    b"en-DK" => &["en-GB"],
    b"en-DM" => &["en-GB"],
    b"en-ER" => &["en-GB"],
    b"en-FI" => &["en-GB"],
    b"en-FJ" => &["en-GB"],
    b"en-FK" => &["en-GB"],
    b"en-FM" => &["en-GB"],
    b"en-GD" => &["en-GB"],
    b"en-GG" => &["en-GB"],
    b"en-GH" => &["en-GB"],
    b"en-GI" => &["en-GB"],
    b"en-GM" => &["en-GB"],
    b"en-GU" => &[
      "en-US", "en-001", "en-AS", "en-CA", "en-MH", "en-MP", "en-PH", "en-PR",
      "en-UM", "en-VI",
    ],
    b"en-GY" => &["en-GB"],
    b"en-HK" => &["en-GB"],
    b"en-IE" => &["en-GB"],
    b"en-IL" => &["en-GB"],
    b"en-IM" => &["en-GB"],
    b"en-IN" => &["en-GB"],
    b"en-IO" => &["en-GB"],
    b"en-JE" => &["en-GB"],
    b"en-JM" => &["en-GB"],
    b"en-KE" => &["en-GB"],
    b"en-KI" => &["en-GB"],
    b"en-KN" => &["en-GB"],
    b"en-KY" => &["en-GB"],
    b"en-LC" => &["en-GB"],
    b"en-LR" => &["en-GB"],
    b"en-LS" => &["en-GB"],
    b"en-MG" => &["en-GB"],
    b"en-MH" => &[
      "en-US", "en-001", "en-AS", "en-CA", "en-GU", "en-MP", "en-PH", "en-PR",
      "en-UM", "en-VI",
    ],
    b"en-MO" => &["en-GB"],
    b"en-MP" => &[
      "en-US", "en-001", "en-AS", "en-CA", "en-GU", "en-MH", "en-PH", "en-PR",
      "en-UM", "en-VI",
    ],
    b"en-MS" => &["en-GB"],
    b"en-MT" => &["en-GB"],
    b"en-MU" => &["en-GB"],
    b"en-MV" => &["en-GB"],
    b"en-MW" => &["en-GB"],
    b"en-MY" => &["en-GB"],
    b"en-NA" => &["en-GB"],
    b"en-NF" => &["en-GB"],
    b"en-NG" => &["en-GB"],
    b"en-NL" => &["en-GB"],
    b"en-NR" => &["en-GB"],
    b"en-NU" => &["en-GB"],
    b"en-NZ" => &["en-GB"],
    b"en-PG" => &["en-GB"],
    b"en-PH" => &[
      "en-US", "en-001", "en-AS", "en-CA", "en-GU", "en-MH", "en-MP", "en-PR",
      "en-UM", "en-VI",
    ],
    b"en-PK" => &["en-GB"],
    b"en-PN" => &["en-GB"],
    b"en-PR" => &[
      "en-US", "en-001", "en-AS", "en-CA", "en-GU", "en-MH", "en-MP", "en-PH",
      "en-UM", "en-VI",
    ],
    b"en-PW" => &["en-GB"],
    b"en-RW" => &["en-GB"],
    b"en-SB" => &["en-GB"],
    b"en-SC" => &["en-GB"],
    b"en-SD" => &["en-GB"],
    b"en-SE" => &["en-GB"],
    b"en-SG" => &["en-GB"],
    b"en-SH" => &["en-GB"],
    b"en-SI" => &["en-GB"],
    b"en-SL" => &["en-GB"],
    b"en-SS" => &["en-GB"],
    b"en-SX" => &["en-GB"],
    b"en-SZ" => &["en-GB"],
    b"en-TC" => &["en-GB"],
    b"en-TK" => &["en-GB"],
    b"en-TO" => &["en-GB"],
    b"en-TT" => &["en-GB"],
    b"en-TV" => &["en-GB"],
    b"en-TZ" => &["en-GB"],
    b"en-UG" => &["en-GB"],
    b"en-UM" => &[
      "en-US", "en-001", "en-AS", "en-CA", "en-GU", "en-MH", "en-MP", "en-PH",
      "en-PR", "en-VI",
    ],
    b"en-US" => &[
      "en-001", "en-AS", "en-CA", "en-GU", "en-MH", "en-MP", "en-PH", "en-PR",
      "en-UM", "en-VI",
    ],
    b"en-VC" => &["en-GB"],
    b"en-VG" => &["en-GB"],
    b"en-VI" => &[
      "en-US", "en-001", "en-AS", "en-CA", "en-GU", "en-MH", "en-MP", "en-PH",
      "en-PR", "en-UM",
    ],
    b"en-VU" => &["en-GB"],
    b"en-WS" => &["en-GB"],
    b"en-ZA" => &["en-GB"],
    b"en-ZM" => &["en-GB"],
    b"en-ZW" => &["en-GB"],
    b"enb" => &["kln"],
    b"eo" => &["en"],
    b"eu" => &["es"],
    b"eyo" => &["kln"],
    b"ffm" => &["ff"],
    b"fo" => &["da"],
    b"fub" => &["ff"],
    b"fue" => &["ff"],
    b"fuf" => &["ff"],
    b"fuh" => &["ff"],
    b"fui" => &["ff"],
    b"fuq" => &["ff"],
    b"fuv" => &["ff"],
    b"fy" => &["nl"],
    b"ga" => &["en"],
    b"gaa" => &["en"],
    b"gan" => &["zh"],
    b"gax" => &["om"],
    b"gd" => &["en"],
    b"gkp" => &["kpe"],
    b"gl" => &["es"],
    b"gn" => &["es"],
    b"gnw" => &["gn"],
    b"gsw" => &["de"],
    b"gu" => &["hi"],
    b"gu-Latn" => &["gu-Gujr"],
    b"gui" => &["gn"],
    b"gun" => &["gn"],
    b"ha" => &["en"],
    b"hae" => &["om"],
    b"hak" => &["zh"],
    b"haw" => &["en"],
    b"hi-Latn" => &["hi-Deva"],
    b"hji" => &["ms"],
    b"hr" => &["bs"],
    b"hsn" => &["zh"],
    b"ht" => &["fr"],
    b"hy" => &["ru"],
    b"hy-Armn" => &["ru-Cyrl"],
    b"ia" => &["en"],
    b"id" => &["ms"],
    b"ida" => &["luy"],
    b"ig" => &["en"],
    b"ikt" => &["iu"],
    b"is" => &["en"],
    b"ja-Hani" => &["ja-Jpan"],
    b"ja-Hira" => &["ja-Jpan", "ja-Hrkt"],
    b"ja-Hrkt" => &["ja-Jpan"],
    b"ja-Kana" => &["ja-Jpan", "ja-Hrkt"],
    b"ja-Latn" => &["ja-Jpan"],
    b"jak" => &["ms"],
    b"jax" => &["ms"],
    b"jv" => &["id"],
    b"ka" => &["en"],
    b"ka-Geor" => &["en-Latn"],
    b"kg" => &["fr"],
    b"kk" => &["ru"],
    b"km" => &["en"],
    b"km-Khmr" => &["en-Latn"],
    b"kn" => &["en"],
    b"kn-Knda" => &["en-Latn"],
    b"kn-Latn" => &["kn-Knda"],
    b"knn" => &["kok"],
    b"ko-Hang" => &["ko-Kore"],
    b"ko-Hani" => &["ko-Kore"],
    b"ko-Jamo" => &["ko-Kore", "ko-Hang"],
    b"kri" => &["en"],
    b"ku" => &["tr"],
    b"kvb" => &["ms"],
    b"kvr" => &["ms"],
    b"kxd" => &["ms"],
    b"ky" => &["ru"],
    b"la" => &["it"],
    b"lb" => &["de"],
    b"lce" => &["ms"],
    b"lcf" => &["ms"],
    b"lg" => &["en"],
    b"liw" => &["ms"],
    b"lkb" => &["luy"],
    b"lko" => &["luy"],
    b"lks" => &["luy"],
    b"ln" => &["fr"],
    b"lo" => &["en"],
    b"lo-Laoo" => &["en-Latn"],
    b"loz" => &["en"],
    b"lri" => &["luy"],
    b"lrm" => &["luy"],
    b"lsm" => &["luy"],
    b"ltg" => &["lv"],
    b"lto" => &["luy"],
    b"lts" => &["luy"],
    b"lua" => &["fr"],
    b"lwg" => &["luy"],
    b"lzh" => &["zh"],
    b"mai" => &["hi"],
    b"max" => &["ms"],
    b"meo" => &["ms"],
    b"mfa" => &["ms"],
    b"mfb" => &["ms"],
    b"mfe" => &["en"],
    b"mg" => &["fr"],
    b"mi" => &["en"],
    b"min" => &["ms"],
    b"ml" => &["en"],
    b"ml-Latn" => &["ml-Mlym"],
    b"ml-Mlym" => &["en-Latn"],
    b"mn" => &["ru"],
    b"mnp" => &["zh"],
    b"mqg" => &["ms"],
    b"mr" => &["hi"],
    b"mr-Latn" => &["mr-Deva"],
    b"ms" => &["id"],
    b"msh" => &["mg"],
    b"msi" => &["ms"],
    b"mt" => &["en"],
    b"mui" => &["ms"],
    b"mvf" => &["mn"],
    b"my" => &["en"],
    b"my-Mymr" => &["en-Latn"],
    b"nan" => &["zh"],
    b"nb" => &["no"],
    b"ne" => &["en"],
    b"ne-Deva" => &["en-Latn"],
    b"nhd" => &["gn"],
    b"niq" => &["kln"],
    b"nle" => &["luy"],
    b"nn" => &["nb", "no"],
    b"nso" => &["en"],
    b"ny" => &["en"],
    b"nyd" => &["luy"],
    b"nyn" => &["en"],
    b"oc" => &["fr"],
    b"oki" => &["kln"],
    b"om" => &["en"],
    b"or" => &["en"],
    b"or-Orya" => &["en-Latn"],
    b"orc" => &["om"],
    b"orn" => &["ms"],
    b"ors" => &["ms"],
    b"pa" => &["en"],
    b"pa-Guru" => &["en-Latn"],
    b"pbt" => &["ps"],
    b"pcm" => &["en"],
    b"pel" => &["ms"],
    b"pga" => &["ar"],
    b"pko" => &["kln"],
    b"ps" => &["en"],
    b"ps-Arab" => &["en-Latn"],
    b"pse" => &["ms"],
    b"pst" => &["ps"],
    b"qu" => &["es"],
    b"qub" => &["qu"],
    b"qud" => &["qu"],
    b"quf" => &["qu"],
    b"qug" => &["qu"],
    b"quh" => &["qu"],
    b"quk" => &["qu"],
    b"qul" => &["qu"],
    b"qup" => &["qu"],
    b"qur" => &["qu"],
    b"qus" => &["qu"],
    b"quw" => &["qu"],
    b"qux" => &["qu"],
    b"quy" => &["qu"],
    b"qva" => &["qu"],
    b"qvc" => &["qu"],
    b"qve" => &["qu"],
    b"qvh" => &["qu"],
    b"qvi" => &["qu"],
    b"qvj" => &["qu"],
    b"qvl" => &["qu"],
    b"qvm" => &["qu"],
    b"qvn" => &["qu"],
    b"qvo" => &["qu"],
    b"qvp" => &["qu"],
    b"qvs" => &["qu"],
    b"qvw" => &["qu"],
    b"qvz" => &["qu"],
    b"qwa" => &["qu"],
    b"qwc" => &["qu"],
    b"qwh" => &["qu"],
    b"qws" => &["qu"],
    b"qxa" => &["qu"],
    b"qxc" => &["qu"],
    b"qxh" => &["qu"],
    b"qxl" => &["qu"],
    b"qxn" => &["qu"],
    b"qxo" => &["qu"],
    b"qxp" => &["qu"],
    b"qxr" => &["qu"],
    b"qxt" => &["qu"],
    b"qxu" => &["qu"],
    b"qxw" => &["qu"],
    b"rag" => &["luy"],
    b"rm" => &["de"],
    b"rn" => &["en"],
    b"rw" => &["fr"],
    b"sa" => &["hi"],
    b"scn" => &["it"],
    b"sd" => &["en"],
    b"sd-Arab" => &["en-Latn"],
    b"sdc" => &["sc"],
    b"sdn" => &["sc"],
    b"sgc" => &["kln"],
    b"sh" => &["bs", "hr", "sr"],
    b"shu" => &["ar"],
    b"si" => &["en"],
    b"si-Sinh" => &["en-Latn"],
    b"skg" => &["mg"],
    b"sn" => &["en"],
    b"so" => &["en"],
    b"spv" => &["or"],
    b"sq" => &["en"],
    b"sr-Latn" => &["sr-Cyrl"],
    b"sro" => &["sc"],
    b"ssh" => &["ar"],
    b"ssy" => &["aa"],
    b"st" => &["en"],
    b"su" => &["id"],
    b"sw" => &["en"],
    b"ta" => &["en"],
    b"ta-Latn" => &["ta-Taml"],
    b"ta-Taml" => &["en-Latn"],
    b"tdx" => &["mg"],
    b"te" => &["en"],
    b"te-Latn" => &["te-Telu"],
    b"te-Telu" => &["en-Latn"],
    b"tec" => &["kln"],
    b"tg" => &["ru"],
    b"ti" => &["en"],
    b"ti-Ethi" => &["en-Latn"],
    b"tk" => &["ru"],
    b"tk-Latn" => &["ru-Cyrl"],
    b"tkg" => &["mg"],
    b"tlh" => &["en"],
    b"tmw" => &["ms"],
    b"tn" => &["en"],
    b"to" => &["en"],
    b"tt" => &["ru"],
    b"tum" => &["en"],
    b"tuy" => &["kln"],
    b"txy" => &["mg"],
    b"ug" => &["zh"],
    b"ur" => &["en"],
    b"ur-Arab" => &["en-Latn"],
    b"urk" => &["ms"],
    b"uz" => &["ru"],
    b"uz-Latn" => &["ru-Cyrl"],
    b"uzs" => &["uz"],
    b"vkk" => &["ms"],
    b"vkt" => &["ms"],
    b"vro" => &["et"],
    b"wo" => &["fr"],
    b"wuu" => &["zh"],
    b"xh" => &["en"],
    b"xmm" => &["ms"],
    b"xmv" => &["mg"],
    b"xmw" => &["mg"],
    b"yi" => &["en"],
    b"yi-Hebr" => &["en-Latn"],
    b"yih" => &["yi"],
    b"yo" => &["en"],
    b"yue" => &["zh"],
    b"za" => &["zh"],
    b"za-Latn" => &["zh-Hans"],
    b"zh-Hani" => &["zh-Hans", "zh-Hant"],
    b"zh-Hans-CN" => &["zh-Hant-HK", "zh-Hant-MO"],
    b"zh-Hant-CN" => &["zh-Hans", "lzh"],
    b"zh-Hant-HK" => &["zh-Hant-MO", "zh-Hans"],
    b"zh-Hant-MO" => &["zh-Hant-HK", "zh-Hans"],
    b"zh-Hant-TW" => &["zh-Hant", "zh-Hans"],
    b"zh-Latn" => &["zh-Hans-CN"],
    b"zlm" => &["ms"],
    b"zmi" => &["ms"],
    b"zu" => &["en"],
    _ => &[],
  }
}
