[package]
name = "glossa-l10n"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
categories.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Glossa Localization Data"

[features]
error = []
yes_no = []

[dependencies]
lang-id = { workspace = true, features = ["consts"] }

[package.metadata.docs.rs]
all-features = true
# rustdoc-args = ["--cfg", "__unstable_doc"]

[lints]
workspace = true
