[package]
name = "glossa-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
categories.workspace = true
# readme = "../../docs/Readme.md"
repository.workspace = true
rust-version.workspace = true
description = "Generate const language localisation map code at compile time"

[features]
default = ["yaml", "toml"]
yaml = ["dep:serde_yml"]
json = ["dep:serde_json"]
json5 = ["dep:serde_json5"]
ron = ["dep:ron"]
toml = ["dep:toml"]
highlight = ["dep:hlight"]

[dependencies]
phf_codegen.workspace = true
getset.workspace = true
log.workspace = true
nom.workspace = true
rayon.workspace = true
anyhow.workspace = true
itertools.workspace = true
walkdir.workspace = true
smallvec.workspace = true
dashmap.workspace = true
ron = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
serde_json5 = { workspace = true, optional = true }
serde_yml = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
hlight = { workspace = true, optional = true }
serde = { workspace = true, features = ["std"] }
kstring = { workspace = true, features = ["serde"] }
lang-id = { workspace = true, features = ["map", "match", "serde", "consts"] }
thiserror = { workspace = true, features = ["std"] }
bincode = { workspace = true, features = ["serde", "std"] }
glossa-shared = { workspace = true, features = ["bincode", "std"] }
tmpl-resolver = { workspace = true, features = ["bincode", "std", "toml"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "__unstable_doc"]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dev-dependencies]
testutils = { workspace = true, features = ["std"] }
# glossa-shared = { workspace = true, features = ["bincode", "std"] }
