#!/usr/bin/env ruby
#
# frozen_string_literal
# ----------------
require_relative 'enter_ci_dir'

argvise_rb = Pathname 'tmp/argvise.rb'

unless (argvise_rb.exist? && argvise_rb.size > 16)
  raise "File #{argvise_rb} does not exist or is empty."
end

[
  '# This file is automatically generated by "https://github.com/2moe/glossa/raw/refs/heads/dev/ci/utils/concat.rb". Please edit with caution.',
  argvise_rb.read,
  File.read('misc/end.rb')
]
  .join("\n")
  .then { File.write('preload.rb', _1) }
