name: build wasi
on:
  {
    "push":
      {
        "paths":
          [
            ".github/workflows/build-wasi.yml",
            "ci/docker.rb",
            "ci/build_wasi.rb",
            "ci/calculate_digest.rb",
          ],
      },
  }

env:
  # it's string, not boolean
  update_releases: "false"
  #
  RELEASE_TAG: "cli@v0.0.1"
  RUBYOPT: "--disable=gems"
  CARGO_TARGET_DIR: target
  BUILDKIT_PROGRESS: plain
  #
  default_ci_shell: ruby ci/preload.rb {0}
  ghcr_repo: ghcr.io/2moe/glossa-cli

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: ${{env.default_ci_shell}}
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v4
        with:
          # ~/.cargo/bin/
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: setup containerd-shim
        run: require_ci 'install_wasm_shim'

      - name: build wasi
        run: |
          require_ci 'build_wasi'
          build_wasi_target

      - name: build & push docker image
        run: |
          require_ci 'docker'
          {
            preset: 'wasi',
          }
            .then { build_and_push_zstd_docker_image **_1 }

      - name: install blake3
        env:
          RUBYOPT: ""
        run: |
          require_ci 'install_gem'
          install_gem

      - name: calculate digest
        env:
          RUBYOPT: ""
        run: |
          require_ci 'calculate_digest'
          calculate_and_output_digests

      - name: release
        uses: softprops/action-gh-release@v2
        if: ${{ fromJSON(env.update_releases) }}
        with:
          fail_on_unmatched_files: true
          tag_name: ${{env.RELEASE_TAG}}
          name: glossa-${{env.RELEASE_TAG}}
          files: |
            release/*.zst
            release/*.json
          body_path: release/digests.md
