name: build wasi
on:
  {
    "push":
      { "paths": [".github/workflows/build-wasi.yml", "ci/wasi.dockerfile"] },
  }

env:
  # it's string, not boolean
  update_releases: "false"
  #
  RELEASE_TAG: "cli@v0.0.1"
  RUBYOPT: "--disable=gems"
  CARGO_TARGET_DIR: target
  BUILDKIT_PROGRESS: plain
  #
  default_ci_shell: ruby cinnabar/ci/preload.rb {0}
  ghcr_repo: ghcr.io/2moe/glossa-cli
  docker_file: ci/wasi.dockerfile
  pkg_name: glossa-cli

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: ${{env.default_ci_shell}}
    steps:
      - uses: actions/checkout@v4

      - name: clone cinnabar
        uses: actions/checkout@v4
        with:
          repository: 2moe/cinnabar
          path: cinnabar

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v4
        with:
          # ~/.cargo/bin/
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: setup containerd-shim
        run: require_ci 'install_wasm_shim'

      - name: build wasi
        run: |
          require_ci 'build_wasi'
          build_wasi_target

      - name: build & push docker image
        run: |
          require_ci 'compression'
          require_ci 'docker/build'
          require_ci 'docker/manifest'

          create_zstd_buildx_machine
          cfg = {
            tag: 'wasi-p1',
            os: 'wasip1',
            arch: 'wasm32',
            docker_repo: '${{env.ghcr_repo}}',
            docker_file: '${{env.docker_file}}',
            pkg_name: '${{env.pkg_name}}',
            suffix: '.wasm',
          }

          cfg2 = {
            tag: 'wasi-p2',
            os: 'wasip2',
          }.then { cfg.merge _1 }

          [cfg, cfg2].each do |x|
            FileCompressor.new(x).compress
            DockerBuild.new(x).build
          end

          {
            repo: cfg[:docker_repo],
            tags: [cfg, cfg2].map { |c| c[:tag] }
          }
            .then { create_and_push_manifest **_1 }

      - name: install blake3
        env:
          RUBYOPT: ""
        run: |
          require_ci 'install_gem'
          install_gem

      - name: calculate digest
        env:
          RUBYOPT: ""
        run: |
          require_ci 'calculate_digest'
          calculate_and_output_digests

      - name: release
        uses: softprops/action-gh-release@v2
        if: ${{ fromJSON(env.update_releases) }}
        with:
          fail_on_unmatched_files: true
          tag_name: ${{env.RELEASE_TAG}}
          name: glossa-${{env.RELEASE_TAG}}
          files: |
            release/*.zst
            release/*.json
          body_path: release/digests.md
